Update semgrep.yml

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -20,4 +20,19 @@ jobs:
       image: returntocorp/semgrep
     steps:
     - uses: actions/checkout@v3
-    - run: semgrep ci --force-color
+    - run: |
+        echo "Running semgrep and dumping results to JSON file"
+        semgrep ci --json --output report-ssc.json || true
+        json_file=report-ssc.json
+        echo "Iterating through findings"
+        findings=$(jq -r '.results[]' "$json_file")
+        for k in $(jq '.results | keys | .[]' "$json_file"); do
+            value=$(jq -r ".results[$k]" "$json_file");
+            echo "$value" > finding_content.json
+            severity=$(jq -r '.extra.severity' "finding_content.json");
+            if [[ $severity == "ERROR" ]]; then
+                echo "Exiting with error code 1"
+                exit 1;
+            fi
+        done
+        echo "There are no critical-high findings"
